### ISSUE TITLE
brew install astartectl

### ISSUE THREAD

**Issue by uptothecloud** [astarte-platform/astartectl#161] opened 2022-08-02 18:59 UTC
When brew is installing astartectl I get many errors:

"/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/sys@v0.0.0-20191010194322-b09406accb47/unix/syscall_darwin.1_13.go:25:3: //go:linkname must refer to declared function or variable

/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/sys@v0.0.0-20191010194322-b09406accb47/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable

/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/sys@v0.0.0-20191010194322-b09406accb47/unix/zsyscall_darwin_amd64.1_13.go:40:3: //go:linkname must refer to declared function or variable

/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/sys@v0.0.0-20191010194322-b09406accb47/unix/zsyscall_darwin_amd64.go:28:3: //go:linkname must refer to declared function or variable

/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/sys@v0.0.0-20191010194322-b09406accb47/unix/zsyscall_darwin_amd64.go:43:3: //go:linkname must refer to declared function or variable

/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/sys@v0.0.0-20191010194322-b09406accb47/unix/zsyscall_darwin_amd64.go:59:3: //go:linkname must refer to declared function or variable

/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/sys@v0.0.0-20191010194322-b09406accb47/unix/zsyscall_darwin_amd64.go:75:3: //go:linkname must refer to declared function or variable

/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/sys@v0.0.0-20191010194322-b09406accb47/unix/zsyscall_darwin_amd64.go:90:3: //go:linkname must refer to declared function or variable

/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/sys@v0.0.0-20191010194322-b09406accb47/unix/zsyscall_darwin_amd64.go:105:3: //go:linkname must refer to declared function or variable

/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/sys@v0.0.0-20191010194322-b09406accb47/unix/zsyscall_darwin_amd64.go:121:3: //go:linkname must refer to declared function or variable

/Library/Caches/Homebrew/go_mod_cache/pkg/mod/golang.org/x/sys@v0.0.0-20191010194322-b09406accb47/unix/zsyscall_darwin_amd64.go:121:3: too many errors"

This is happening on multiple machines. Is there an issue with the install file?

Thank you

**Comment by Annopaolo** [comment] 2022-12-14 09:16
Hi @uptothecloud, the astartectl formula has been updated to the latest version. Could you please check if the issue is still present?

**Comment by Annopaolo** [comment] 2023-02-27 13:42
Closing this, @uptothecloud feel free to let us know you are still experiencing the issue!

**Closed by Annopaolo** 2023-02-27 13:42 UTC
